# Generated by Django 4.1.3 on 2022-12-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_useranswer_delete_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='status',
            field=models.CharField(choices=[('unanswered', 'Unanswered'), ('correct', 'Correct'), ('incorrect', 'Incorrect'), ('current', 'Current')], max_length=50),
        ),
    ]
